name: plexmediaserver
version: 1.13.2.5102-4898d7d96
summary: Unofficial snap for the Plex media server
architectures: [armhf]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/
confinement: devmode
grade: devel

apps:
  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - home
      - log-observe
      - mount-observe
      - network-bind
      - network
      - removable-media

parts:
  common:
    plugin: dump
    source: bin
    organize:
      server.sh: bin/server.sh
  plexmediaserver:
    plugin: make
    source: .
    build-packages: [wget]
    stage-packages: [libicu55]
