name: plexmediaserver
version: 1.16.1.1273-4b6101f87
summary: Unofficial snap for the Plex media server
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/
confinement: devmode
grade: devel

architectures:
    - build-on:
        - armhf

apps:
  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - home
      - log-observe
      - mount-observe
      - network-bind
      - network
      - removable-media

parts:
  common:
    plugin: dump
    source: bin
    organize:
      server.sh: bin/server.sh
  plexmediaserver:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server-new/${SNAPCRAFT_PROJECT_VERSION}/debian/plexmediaserver_${SNAPCRAFT_PROJECT_VERSION}_armhf.deb
    stage-packages: [libicu55]
  snapcraft-preload:
   source: https://github.com/sergiusens/snapcraft-preload.git
   build-packages: [build-essential]
   plugin: cmake
